# Generated by Django 2.2 on 2020-01-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emojirama', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emojirama',
            options={'ordering': ('id',)},
        ),
    ]
