# Generated by Django 2.2 on 2020-01-18 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emojirama', '0002_auto_20200105_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='emojirama',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emojirama_emojirama_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emojirama',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emojirama',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emojirama_emojirama_modifiedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emojirama',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
