# Generated by Django 2.2 on 2020-01-24 03:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict
            ),
        ),
    ]
